apiVersion: v1
kind: Secret
metadata:
  name: matching-secrets
  namespace: matching-system
type: Opaque
data:
  postgres_password: Educify!= # base64 encoded 'password'
  redis_password: ""
  api_key: YXBpa2V5MTIz # base64 encoded api key
